version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/JanMa/openbao-plugin-secrets-nomad/nomad.pluginVersion=v{{.Version}}

archives:
  - format: zip
    files:
      - none*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

signs:
  - artifacts: checksum
    args:
      [
        "-u",
        "jan@martens.eu.org",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
